### ISSUE TITLE
🍣参加表明🍕

### ISSUE THREAD

**Issue by yymm** [DevIPL/2015summer#1]
参加される方はﾁｪｯｸ
- [x] @yymm
- [x] @doragon 
- [x] @hashrock 
- [x] @ym19851201 
- [x] @3100 
- [ ] @sotoattanito

**Comment by yymm** [comment]
アカウントわからない方いますが、各自追加お願いします。

**Comment by 3100** [comment]
iosからチェックできない説。参加します。

**Comment by doragon** [comment]
チェックボックスとか作れたんですか。初めて知りました笑

**Comment by 3100** [comment]
:sushi:

**Comment by yymm** [comment]
@sotoattanitoさん追加しました

**Comment by sotoattanito** [comment]
ありがとうございます

**Comment by yymm** [comment]
6/1 or 6/8 or 6/15

になりそうです。

日程絞りたいので、この日ダメって言う方書き込みお願いします。
